name: Test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      time:
        type: string
        default: '30'
        description: 'who cares'
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: sleep ${{ github.event.inputs.time }}
